# Generated by Django 3.0.3 on 2020-02-08 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name of the experiment, to be used as a reference')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, verbose_name='Date of creation of the experiment object')),
                ('status', models.CharField(choices=[('N', 'New'), ('R', 'Running'), ('P', 'Paused'), ('D', 'Finished')], default='N', editable=False, max_length=1, verbose_name='Execution status for this experiment, 1 character among the available options')),
                ('taskid', models.IntegerField(default=-1, editable=False, verbose_name='Identifier of the task launched with Celery for the experiment execution')),
            ],
        ),
    ]
