# Generated by Django 3.0.3 on 2020-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskid',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True, verbose_name='Identifier of the task launched with Celery for the experiment execution'),
        ),
    ]
