# Generated by Django 3.0.3 on 2020-02-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20200209_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='created',
        ),
    ]
