# Generated by Django 3.0.3 on 2020-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_auto_20200227_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Running'), ('P', 'Paused'), ('D', 'Finished')], default='R', editable=False, max_length=1, verbose_name='Execution status for this experiment, 1 character among the available options'),
        ),
    ]
