# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG = nano
AVRDUDE_ARD_PROGRAMMER = uncompatino
AVRDUDE_ARD_BAUDRATE = 9600
AVRDUDE_CONF = /etc/avrdude.conf

include $(ARDMK_DIR)/Arduino.mk